import { IDropDownList } from "./interfaces/currencies";

export const currency_list: IDropDownList[] = [
    { "country": "Afghanistan", "name": "Afghan Afghani", "code": "AFA", "symbol": "؋" },
    { "country": "Algeria", "name": "Algerian Dinar", "code": "DZD", "symbol": "دج" },
    { "country": "Angola", "name": "Angolan Kwanza", "code": "AOA", "symbol": "Kz" },
    { "country": "Argentina", "name": "Argentine Peso", "code": "ARS", "symbol": "$" },
    { "country": "Armenia", "name": "Armenian Dram", "code": "AMD", "symbol": "֏" },
    { "country": "Aruba", "name": "Aruban Florin", "code": "AWG", "symbol": "ƒ" },
    { "country": "Australia", "name": "Australian Dollar", "code": "AUD", "symbol": "$" },
    { "country": "Azerbaijan", "name": "Azerbaijani Manat", "code": "AZN", "symbol": "m" },
    { "country": "Bahamas", "name": "Bahamian Dollar", "code": "BSD", "symbol": "B$" },
    { "country": "Bahrain", "name": "Bahraini Dinar", "code": "BHD", "symbol": ".د.ب" },
    { "country": "Bangladesh", "name": "Bangladeshi Taka", "code": "BDT", "symbol": "৳" },
    { "country": "Barbados", "name": "Barbadian Dollar", "code": "BBD", "symbol": "Bds$" },
    { "country": "Belarus", "name": "Belarusian Ruble", "code": "BYR", "symbol": "Br" },
    { "country": "Belgium", "name": "Belgian Franc", "code": "BEF", "symbol": "fr" },
    { "country": "Belize", "name": "Belize Dollar", "code": "BZD", "symbol": "$" },
    { "country": "Bermuda", "name": "Bermudan Dollar", "code": "BMD", "symbol": "$" },
    { "country": "Bhutan", "name": "Bhutanese Ngultrum", "code": "BTN", "symbol": "Nu." },
    { "country": "Bolivia", "name": "Bolivian Boliviano", "code": "BOB", "symbol": "Bs." },
    { "country": "Bosnia and Herzegovina", "name": "Bosnia-Herzegovina Convertible Mark", "code": "BAM", "symbol": "KM" },
    { "country": "Botswana", "name": "Botswanan Pula", "code": "BWP", "symbol": "P" },
    { "country": "Brazil", "name": "Brazilian Real", "code": "BRL", "symbol": "R$" },
    { "country": "British Indian Ocean Territory", "name": "British Pound Sterling", "code": "GBP", "symbol": "£" },
    { "country": "Brunei Darussalam", "name": "Brunei Dollar", "code": "BND", "symbol": "B$" },
    { "country": "Bulgaria", "name": "Bulgarian Lev", "code": "BGN", "symbol": "Лв." },
    { "country": "Burundi", "name": "Burundian Franc", "code": "BIF", "symbol": "FBu" },
    { "country": "Cambodia", "name": "Cambodian Riel", "code": "KHR", "symbol": "KHR" },
    { "country": "Canada", "name": "Canadian Dollar", "code": "CAD", "symbol": "$" },
    { "country": "Cape Verde", "name": "Cape Verdean Escudo", "code": "CVE", "symbol": "$" },
    { "country": "Cayman Islands", "name": "Cayman Islands Dollar", "code": "KYD", "symbol": "$" },
    { "country": "Chile", "name": "Chilean Peso", "code": "CLP", "symbol": "$" },
    { "country": "China", "name": "Chinese Yuan", "code": "CNY", "symbol": "¥" },
    { "country": "Colombia", "name": "Colombian Peso", "code": "COP", "symbol": "$" },
    { "country": "Comoros", "name": "Comorian Franc", "code": "KMF", "symbol": "CF" },
    { "country": "Congo", "name": "Congolese Franc", "code": "CDF", "symbol": "FC" },
    { "country": "Costa Rica", "name": "Costa Rican ColÃ³n", "code": "CRC", "symbol": "₡" },
    { "country": "Croatia", "name": "Croatian Kuna", "code": "HRK", "symbol": "kn" },
    { "country": "Cuba", "name": "Cuban Convertible Peso", "code": "CUC", "symbol": "$, CUC" },
    { "country": "Czech Republic", "name": "Czech Republic Koruna", "code": "CZK", "symbol": "Kč" },
    { "country": "Denmark", "name": "Danish Krone", "code": "DKK", "symbol": "Kr." },
    { "country": "Djibouti", "name": "Djiboutian Franc", "code": "DJF", "symbol": "Fdj" },
    { "country": "Dominican Republic", "name": "Dominican Peso", "code": "DOP", "symbol": "$" },
    { "country": "Egypt", "name": "Egyptian Pound", "code": "EGP", "symbol": "ج.م" },
    { "country": "Eritrea", "name": "Eritrean Nakfa", "code": "ERN", "symbol": "Nfk" },
    { "country": "Estonia", "name": "Estonian Kroon", "code": "EEK", "symbol": "kr" },
    { "country": "Ethiopia", "name": "Ethiopian Birr", "code": "ETB", "symbol": "Nkf" },
    { "country": "Euro", "name": "Euro", "code": "EUR", "symbol": "€" },
    { "country": "Falkland Islands (Malvinas)", "name": "Falkland Islands Pound", "code": "FKP", "symbol": "£" },
    { "country": "Fiji", "name": "Fijian Dollar", "code": "FJD", "symbol": "FJ$" },
    { "country": "France", "name": "French Euro", "code": "EUR", "symbol": "€" },
    { "country": "Finland", "name": "Finland Euro", "code": "EUR", "symbol": "€" },
    { "country": "Gambia", "name": "Gambian Dalasi", "code": "GMD", "symbol": "D" },
    { "country": "Georgia", "name": "Georgian Lari", "code": "GEL", "symbol": "ლ" },
    { "country": "Germany", "name": "German Euro", "code": "DE", "symbol": "€" },
    { "country": "Ghana", "name": "Ghanaian Cedi", "code": "GHS", "symbol": "GH₵" },
    { "country": "Gibraltar", "name": "Gibraltar Pound", "code": "GIP", "symbol": "£" },
    { "country": "Greece", "name": "Greek Drachma", "code": "GRD", "symbol": "Δρ" },
    { "country": "Guatemala", "name": "Guatemalan Quetzal", "code": "GTQ", "symbol": "Q" },
    { "country": "Guinea", "name": "Guinean Franc", "code": "GNF", "symbol": "FG" },
    { "country": "Guyana", "name": "Guyanaese Dollar", "code": "GYD", "symbol": "$" },
    { "country": "Greenland", "name": "Danish Krone", "code": "DKK", "symbol": "Kr." },
    { "country": "Haiti", "name": "Haitian Gourde", "code": "HTG", "symbol": "G" },
    { "country": "Honduras", "name": "Honduran Lempira", "code": "HNL", "symbol": "L" },
    { "country": "Hong Kong", "name": "Hong Kong Dollar", "code": "HKD", "symbol": "$" },
    { "country": "Hungary", "name": "Hungarian Forint", "code": "HUF", "symbol": "Ft" },
    { "country": "Iceland", "name": "Icelandic KrÃ³na", "code": "ISK", "symbol": "kr" },
    { "country": "India", "name": "Indian Rupee", "code": "INR", "symbol": "₹" },
    { "country": "Indonesia", "name": "Indonesian Rupiah", "code": "IDR", "symbol": "Rp" },
    { "country": "Iran", "name": "Iranian Rial", "code": "IRR", "symbol": "﷼" },
    { "country": "Iraq", "name": "Iraqi Dinar", "code": "IQD", "symbol": "د.ع" },
    { "country": "Israel", "name": "Israeli New Sheqel", "code": "ILS", "symbol": "₪" },
    { "country": "Italy", "name": "Italian Lira", "code": "ITL", "symbol": "L" },
    { "country": "Jamaica", "name": "Jamaican Dollar", "code": "JMD", "symbol": "J$" },
    { "country": "Japan", "name": "Japanese Yen", "code": "JPY", "symbol": "¥" },
    { "country": "Jordan", "name": "Jordanian Dinar", "code": "JOD", "symbol": "ا.د" },
    { "country": "Kazakhstan", "name": "Kazakhstani Tenge", "code": "KZT", "symbol": "лв" },
    { "country": "Kenya", "name": "Kenyan Shilling", "code": "KES", "symbol": "KSh" },
    { "country": "Kuwait", "name": "Kuwaiti Dinar", "code": "KWD", "symbol": "ك.د" },
    { "country": "Kyrgyzstan", "name": "Kyrgystani Som", "code": "KGS", "symbol": "лв" },
    { "country": "Lao People's Democratic Republic", "name": "Laotian Kip", "code": "LAK", "symbol": "₭" },
    { "country": "Latvia", "name": "Latvian Lats", "code": "LVL", "symbol": "Ls" },
    { "country": "Lebanon", "name": "Lebanese Pound", "code": "LBP", "symbol": "£" },
    { "country": "Lesotho", "name": "Lesotho Loti", "code": "LSL", "symbol": "L" },
    { "country": "Liberia", "name": "Liberian Dollar", "code": "LRD", "symbol": "$" },
    { "country": "Libyan Arab Jamahiriya", "name": "Libyan Dinar", "code": "LYD", "symbol": "د.ل" },
    { "country": "Lithuania", "name": "Lithuanian Litas", "code": "LTL", "symbol": "Lt" },
    { "country": "Macao", "name": "Macanese Pataca", "code": "MOP", "symbol": "$" },
    { "country": "Macedonia", "name": "Macedonian Denar", "code": "MKD", "symbol": "ден" },
    { "country": "Mali", "name": "Malagasy Ariary", "code": "MGA", "symbol": "Ar" },
    { "country": "Malawi", "name": "Malawian Kwacha", "code": "MWK", "symbol": "MK" },
    { "country": "Malaysia", "name": "Malaysian Ringgit", "code": "MYR", "symbol": "RM" },
    { "country": "Maldives", "name": "Maldivian Rufiyaa", "code": "MVR", "symbol": "Rf" },
    { "country": "Mauritania", "name": "Mauritanian Ouguiya", "code": "MRO", "symbol": "MRU" },
    { "country": "Mauritius", "name": "Mauritian Rupee", "code": "MUR", "symbol": "₨" },
    { "country": "Mexico", "name": "Mexican Peso", "code": "MXN", "symbol": "$" },
    { "country": "Moldova", "name": "Moldovan Leu", "code": "MDL", "symbol": "L" },
    { "country": "Mongolia", "name": "Mongolian Tugrik", "code": "MNT", "symbol": "₮" },
    { "country": "Morocco", "name": "Moroccan Dirham", "code": "MAD", "symbol": "MAD" },
    { "country": "Mozambique", "name": "Mozambican Metical", "code": "MZM", "symbol": "MT" },
    { "country": "Myanmar", "name": "Myanmar Kyat", "code": "MMK", "symbol": "K" },
    { "country": "Namibia", "name": "Namibian Dollar", "code": "NAD", "symbol": "$" },
    { "country": "Nepal", "name": "Nepalese Rupee", "code": "NPR", "symbol": "₨" },
    { "country": "Netherlands", "name": "Netherlands Antillean Guilder", "code": "ANG", "symbol": "ƒ" },
    { "country": "New Taiwan", "name": "New Taiwan Dollar", "code": "TWD", "symbol": "$" },
    { "country": "New Zealand", "name": "New Zealand Dollar", "code": "NZD", "symbol": "$" },
    { "country": "Nicaragua", "name": "Nicaraguan CÃ³rdoba", "code": "NIO", "symbol": "C$" },
    { "country": "Nigeria", "name": "Nigerian Naira", "code": "NGN", "symbol": "₦" },
    { "country": "North Korea", "name": "North Korean Won", "code": "KPW", "symbol": "₩" },
    { "country": "Norway", "name": "Norwegian Krone", "code": "NOK", "symbol": "kr" },
    { "country": "Oman", "name": "Omani Rial", "code": "OMR", "symbol": ".ع.ر" },
    { "country": "Pakistan", "name": "Pakistani Rupee", "code": "PKR", "symbol": "₨" },
    { "country": "Panama", "name": "Panamanian Balboa", "code": "PAB", "symbol": "B/." },
    { "country": "Papua New Guinea", "name": "Papua New Guinean Kina", "code": "PGK", "symbol": "K" },
    { "country": "Paraguay", "name": "Paraguayan Guarani", "code": "PYG", "symbol": "₲" },
    { "country": "Peru", "name": "Peruvian Nuevo Sol", "code": "PEN", "symbol": "S/." },
    { "country": "Philippines", "name": "Philippine Peso", "code": "PHP", "symbol": "₱" },
    { "country": "Poland", "name": "Polish Zloty", "code": "PLN", "symbol": "zł" },
    { "country": "Portugal", "name": "Portugal Euro", "code": "EUR", "symbol": "€" },
    { "country": "Qatar", "name": "Qatari Rial", "code": "QAR", "symbol": "ق.ر" },
    { "country": "Romania", "name": "Romanian Leu", "code": "RON", "symbol": "lei" },
    { "country": "Russian Federation", "name": "Russian Ruble", "code": "RUB", "symbol": "₽" },
    { "country": "Rwanda", "name": "Rwandan Franc", "code": "RWF", "symbol": "FRw" },
    { "country": "Samoa", "name": "Samoan Tala", "code": "WST", "symbol": "SAT" },
    { "country": "Saudi Arabia", "name": "Saudi Riyal", "code": "SAR", "symbol": "﷼" },
    { "country": "Serbia", "name": "Serbian Dinar", "code": "RSD", "symbol": "din" },
    { "country": "Seychelles", "name": "Seychellois Rupee", "code": "SCR", "symbol": "SRe" },
    { "country": "Sierra Leone", "name": "Sierra Leonean Leone", "code": "SLL", "symbol": "Le" },
    { "country": "Singapore", "name": "Singapore Dollar", "code": "SGD", "symbol": "$" },
    { "country": "Slovakia", "name": "Slovak Koruna", "code": "SKK", "symbol": "Sk" },
    { "country": "Solomon Islands", "name": "Solomon Islands Dollar", "code": "SBD", "symbol": "Si$" },
    { "country": "Somalia", "name": "Somali Shilling", "code": "SOS", "symbol": "Sh.so." },
    { "country": "South Africa", "name": "South African Rand", "code": "ZAR", "symbol": "R" },
    { "country": "South Korea", "name": "South Korean Won", "code": "KRW", "symbol": "₩" },
    { "country": "Sri Lanka", "name": "Sri Lankan Rupee", "code": "LKR", "symbol": "Rs" },
    { "country": "Sudan", "name": "Sudanese Pound", "code": "SDG", "symbol": ".س.ج" },
    { "country": "Suriname", "name": "Surinamese Dollar", "code": "SRD", "symbol": "$" },
    { "country": "Spain", "name": "", "code": "EUR", "symbol": "£" },
    { "country": "Swaziland", "name": "Swazi Lilangeni", "code": "SZL", "symbol": "E" },
    { "country": "Sweden", "name": "Swedish Krona", "code": "SEK", "symbol": "kr" },
    { "country": "Switzerland", "name": "Swiss Franc", "code": "CHF", "symbol": "CHf" },
    { "country": "Syrian Arab Republic", "name": "Syrian Pound", "code": "SYP", "symbol": "LS" },
    { "country": "Tajikistan", "name": "Tajikistani Somoni", "code": "TJS", "symbol": "SM" },
    { "country": "Tanzania", "name": "Tanzanian Shilling", "code": "TZS", "symbol": "TSh" },
    { "country": "Thailand", "name": "Thai Baht", "code": "THB", "symbol": "฿" },
    { "country": "Tonga", "name": "Tongan Pa'anga", "code": "TOP", "symbol": "$" },
    { "country": "Trinidad and Tobago", "name": "Trinidad & Tobago Dollar", "code": "TTD", "symbol": "$" },
    { "country": "Tunisia", "name": "Tunisian Dinar", "code": "TND", "symbol": "ت.د" },
    { "country": "Turkey", "name": "Turkish Lira", "code": "TRY", "symbol": "₺" },
    { "country": "Uganda", "name": "Ukrainian Hryvnia", "code": "UAH", "symbol": "USh" },
    { "country": "Ukraine", "name": "Ugandan Shilling", "code": "UGX", "symbol": "₴" },
    { "country": "United Arab Emirates", "name": "United Arab Emirates dirham", "code": "AED", "symbol": "د.إ" },
    { "country": "United Kingdom", "name": "British pound", "code": "GBP", "symbol": "£" },
    { "country": "United States", "name": "US Dollar", "code": "USD", "symbol": "$" },
    { "country": "Turkmenistan", "name": "Turkmenistani Manat", "code": "TMT", "symbol": "T" },
    { "country": "Uruguay", "name": "Uruguayan Peso", "code": "UYU", "symbol": "$" },
    { "country": "Vanuatu", "name": "Vanuatu Vatu", "code": "VUV", "symbol": "VT" },
    { "country": "Uzbekistan", "name": "Uzbekistan Som", "code": "UZS", "symbol": "лв" },
    { "country": "Vietnam", "name": "Vietnamese Dong", "code": "VND", "symbol": "₫" },
    { "country": "Venezuela", "name": "Venezuelan BolÃvar", "code": "VEF", "symbol": "Bs" },
    { "country": "Zambia", "name": "Zambian Kwacha", "code": "ZMK", "symbol": "ZK" },
    { "country": "Yemen", "name": "Yemeni Rial", "code": "YER", "symbol": "﷼" }
];